apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wekan-hooks.fullname" . }}
  labels:
{{ include "wekan-hooks.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wekan-hooks.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wekan-hooks.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: "GRAPHQL_URL"
              valueFrom:
                secretKeyRef:
                  key:  GRAPHQL_URL
                  name: {{ .Release.Name }}-auth
            - name: "USER"
              valueFrom:
                secretKeyRef:
                  key:  USER
                  name: {{ .Release.Name }}-auth
            - name: "PASS"
              valueFrom:
                secretKeyRef:
                  key:  PASS
                  name: {{ .Release.Name }}-auth
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
