apiVersion: v1
kind: Service
metadata:
  name: efetch
spec:
  selector:
    app: efetch
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: efetch
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: efetch
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: efetch
    spec:
      containers:
      - image: atilaromero/efetch
        imagePullPolicy: IfNotPresent
        name: efetch
        command: ["efetch"]
        args: ["--address=0.0.0.0"]
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /mnt/cloud/operacoes
          name: operacoes
        - mountPath: /operacoes
          name: operacoes
      volumes:
      - cephfs:
          monitors:
          - 192.168.2.42:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: /operacoes/
          readOnly: true
        name: operacoes
