apiVersion: v1
kind: Service
metadata:
  name: lazyui
spec:
  selector:
    app: lazyui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lazyui-daemon
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lazyui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lazyui
    spec:
      containers:
      - image: swaggerapi/swagger-ui
        imagePullPolicy: IfNotPresent
        name: lazyui
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PORT
          value: "80"
        - name: API_URL
          value: http://sardcloud08:31544/swagger.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: lazyworker
spec:
  selector:
    app: lazyworker
    version: 2.3.10-3.16.2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lazyworker-2.3.10-3.16.2
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lazyworker
      version: 2.3.10-3.16.2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lazyworker
        version: 2.3.10-3.16.2
    spec:
      containers:
      - image: 192.168.2.191:5001/ipeddocker/worker-go:2.3.10-3.16.2_apfs
        imagePullPolicy: IfNotPresent
        name: lazyworker
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "12"
            memory: 32Gi
          requests:
            cpu: "12"
            memory: 32Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: IPEDJAR
          value: /root/IPED/iped/iped.jar
        - name: LOCK_URL
          value: http://$(LOCKER_SERVICE_HOST):$(LOCKER_SERVICE_PORT)
        - name: NOTIFY_URL
          value: http://$(WEKAN_NOTIFIER_SERVICE_HOST):$(WEKAN_NOTIFIER_SERVICE_PORT)
        volumeMounts:
        - mountPath: /mnt/ipedtmp
          name: ipedtmp
        - mountPath: /mnt/cloud/operacoes
          name: operacoes
        - mountPath: /operacoes
          name: operacoes
        - mountPath: /mnt/led
          name: led
        - mountPath: /mnt/kff
          name: kff
        - mountPath: /mnt/PhotoDNA
          name: photodna
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/ipedtmp/
          type: Directory
        name: ipedtmp
      - cephfs:
          monitors:
          - 192.168.2.42:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: /operacoes/
        name: operacoes
      - cephfs:
          monitors:
          - 192.168.2.42:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: /led/V1.24.00
        name: led
      - cephfs:
          monitors:
          - 192.168.2.42:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: /kff/iped-kff-1.2
        name: kff
      - cephfs:
          monitors:
          - 192.168.2.42:6789
          user: admin
          secretRef:
            name: ceph-secret
          path: /PhotoDNA
        name: photodna
