kind: Service
apiVersion: v1
metadata:
  name: locker
spec:
  selector:
    app: locker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locker
  labels:
    app: locker
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: locker
    spec:
      containers:
      - name: locker
        image: 192.168.2.191:5001/ipeddocker/locker:1.1.2
        ports:
        - containerPort: 80

