apiVersion: v1
kind: Service
metadata:
  name: mongo-notifier
spec:
  selector:
    app: mongo-notifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-notifier
  labels:
    app: mongo-watcher
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-notifier
    spec:
      containers:
      - name: mongo-notifier
        image: ipeddocker/mongo-notifier:1.0.1
        ports:
        - containerPort: 80
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-notifier
              key: MONGO_URL

