apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: am-pipeline-data
  name: am-pipeline-data
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
