apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: archivematica-storage-service-staging-data
  name: archivematica-storage-service-staging-data
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi

