apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/atila.alr/go/bin/kompose convert -f docker-compose.yml
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: archivematica-mcp-client
  name: archivematica-mcp-client
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: archivematica-mcp-client
    spec:
      containers:
      - env:
        - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE
          value: MCP
        - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST
          value: $(MYSQL_SERVICE_HOST)
        - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD
          value: demo
        - name: ARCHIVEMATICA_MCPCLIENT_CLIENT_USER
          value: archivematica
        - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT
          value: "true"
        - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CLAMAV_SERVER
          value: $(CLAMAVD_SERVICE_HOST):$(CLAMAVD_SERVICE_PORT)
        - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_ELASTICSEARCHSERVER
          value: $(ELASTICSEARCH_SERVICE_HOST):$(ELASTICSEARCH_SERVICE_PORT)
        - name: ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_MCPARCHIVEMATICASERVER
          value: $(GEARMAN_SERVICE_HOST):$(GEARMAN_SERVICE_PORT)
        - name: ARCHIVEMATICA_MCPCLIENT_SEARCH_ENABLED
          value: "true"
        - name: DJANGO_SECRET_KEY
          value: "12345"
        - name: DJANGO_SETTINGS_MODULE
          value: settings.common
        - name: NAILGUN_PORT
          value: $(FITS_SERVICE_PORT)
        - name: NAILGUN_SERVER
          value: $(FITS_SERVICE_HOST)
        image: 192.168.2.191:5001/archivematica-mcp-client:setec-1.0.0
        name: archivematica-mcp-client
        resources: {}
        volumeMounts:
        - mountPath: /var/archivematica/sharedDirectory
          name: am-pipeline-data
      restartPolicy: Always
      volumes:
      - name: am-pipeline-data
        persistentVolumeClaim:
          claimName: am-pipeline-data
status: {}
