apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: storage
  name: storage
spec:
  ports:
  - name: default
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: storage
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/atila.alr/go/bin/kompose convert -f docker-compose.yml
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: storage
    spec:
      containers:
      - env:
        - name: DJANGO_SETTINGS_MODULE
          value: storage_service.settings.local
        - name: FORWARDED_ALLOW_IPS
          value: '*'
        - name: SS_DB_URL
          value: mysql://$(MYSQL_SERVICE_HOST):demo@mysql/SS
        - name: SS_GNUPG_HOME_PATH
          value: /src/
        - name: SS_GUNICORN_ACCESSLOG
          value: /dev/null
        - name: SS_GUNICORN_RELOAD
          value: "true"
        - name: SS_GUNICORN_RELOAD_ENGINE
          value: auto
        image: 192.168.2.191:5001/archivematica-storage-service:setec-1.0.0
        name: storage
        resources: {}
        volumeMounts:
        - mountPath: /var/archivematica/sharedDirectory
          name: am-pipeline-data
        - mountPath: /var/archivematica/storage-service
          name: archivematica-storage-service-staging-data
        - mountPath: /home
          name: ss-location-data
      restartPolicy: Always
      volumes:
      - name: am-pipeline-data
        persistentVolumeClaim:
          claimName: am-pipeline-data
      - name: archivematica-storage-service-staging-data
        persistentVolumeClaim:
          claimName: archivematica-storage-service-staging-data
      - name: ss-location-data
        persistentVolumeClaim:
          claimName: ss-location-data
status: {}
