apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/atila.alr/go/bin/kompose convert -f docker-compose.yml
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gearman
  name: gearman
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gearman
    spec:
      containers:
      - image: artefactual/gearmand:1.1.17-alpine
        command: 
        - gearmand
        args:
        - --queue-type=redis
        - --redis-server=$(REDIS_SERVICE_HOST)
        - --redis-port=$(REDIS_SERVICE_PORT)
        name: gearman
        ports:
        - containerPort: 4730
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/atila.alr/go/bin/kompose convert -f docker-compose.yml
    kompose.version: 1.15.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: gearman
  name: gearman
spec:
  ports:
  - name: default
    port: 4730
    targetPort: 4730
  selector:
    io.kompose.service: gearman
status:
  loadBalancer: {}
---
