apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ include "ipedworker.fullname" . }}
  labels:
{{ include "ipedworker.labels" . | indent 4 }}
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: OnDelete
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ipedworker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ipedworker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: {{ .Values.image.tag }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              hostPort: 10081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
